# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on: [push, pull_request]

# env has to be set, since git repo doesn't contain legit .env file
env:
  BNETID: "12345678901234567890123456789012" 
  BNETKEY: "12345678901234567890123456789012"
  WCLKEY: "12345678901234567890123456789012"
  WOWREGION: "eu"
  WOWREALM: "stormscale"
  WOWGUILD: "pulumafia"
  WOWLOCALE: "en_US"
  WOWNAMESPACE: "profile-eu"
  MONGOURL: "http://localhost"
  MONGOPORT: 27107
  MONGOUSER: "asd"
  MONGOPWD: "fgh"
  RAIDERRANK: 3
  FLASK_SECRET_KEY: "ahjdkjhagsdgaud786876dajikhakbs6t"
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
